# This is a basic workflow to help you get started with Actions

name: LEADTIME

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    calculate_lead_time_job:
        runs-on: ubuntu-latest
        name: Calculate Lead Time For Change
        steps:
        -   name: calculate lead time for change action step
            id: lead-time
            uses: SE06-Glasgow-University/lead-time-for-change-action@v1.3
            with:
                auth-token: ${{ secrets.GITHUB_TOKEN }}
                web-token: ${{ secrets.LEAD_TIME_AUTH_TOKEN }}
                calculate-previous-releases: true
                number-of-releases: 4
                
        -   name: output lead time for change
            run: echo "The lead time for change in days is ${{ steps.lead-time.outputs.lead-time-for-change }}"
